// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateEvent(arg1:models.EventInput):Promise<models.Event>;

export function DeleteEvent(arg1:number):Promise<void>;

export function GetEvents(arg1:string,arg2:string):Promise<Array<models.Event>>;

export function UpdateEvent(arg1:number,arg2:models.EventInput):Promise<models.Event>;
