// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEvent(arg1) {
  return window['go']['main']['CalendarApp']['CreateEvent'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['CalendarApp']['DeleteEvent'](arg1);
}

export function GetEvents(arg1, arg2) {
  return window['go']['main']['CalendarApp']['GetEvents'](arg1, arg2);
}

export function UpdateEvent(arg1, arg2) {
  return window['go']['main']['CalendarApp']['UpdateEvent'](arg1, arg2);
}
