// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAISync() {
  return window['go']['main']['AISyncApp']['CancelAISync']();
}

export function GetAISyncSetup() {
  return window['go']['main']['AISyncApp']['GetAISyncSetup']();
}

export function GetAISyncStatus() {
  return window['go']['main']['AISyncApp']['GetAISyncStatus']();
}

export function GetSourceEmail(arg1) {
  return window['go']['main']['AISyncApp']['GetSourceEmail'](arg1);
}

export function SaveAISettings(arg1) {
  return window['go']['main']['AISyncApp']['SaveAISettings'](arg1);
}

export function SaveEmailAccount(arg1) {
  return window['go']['main']['AISyncApp']['SaveEmailAccount'](arg1);
}

export function StartAISync() {
  return window['go']['main']['AISyncApp']['StartAISync']();
}

export function TestEmailAccount(arg1) {
  return window['go']['main']['AISyncApp']['TestEmailAccount'](arg1);
}
