// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ai_sync} from '../models';
import {email} from '../models';

export function CancelAISync():Promise<boolean>;

export function GetAISyncSetup():Promise<main.AISyncSetup>;

export function GetAISyncStatus():Promise<ai_sync.Status>;

export function GetSourceEmail(arg1:string):Promise<email.Message>;

export function SaveAISettings(arg1:ai_sync.Settings):Promise<void>;

export function SaveEmailAccount(arg1:email.AccountInput):Promise<email.Account>;

export function StartAISync():Promise<ai_sync.Status>;

export function TestEmailAccount(arg1:email.AccountInput):Promise<void>;
