// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {calendar} from '../models';

export function CreateEvent(arg1:calendar.EventInput):Promise<calendar.Event>;

export function DeleteEvent(arg1:number):Promise<void>;

export function GetEvents(arg1:string,arg2:string):Promise<Array<calendar.Event>>;

export function UpdateEvent(arg1:number,arg2:calendar.EventInput):Promise<calendar.Event>;
